.TH "IntRangeVariableEditor" 3 "Mon Oct 8 2018" "Shared Variable Save System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IntRangeVariableEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits Editor\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInspectorGUI\fP ()"
.br
.ti -1c
.RI "override Texture2D \fBRenderStaticPreview\fP (string assetPath, Object[] subAssets, int width, int height)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file IntRangeVariableEditor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Shared Variable Save System from the source code\&.
