.TH "IntVariable" 3 "Mon Oct 8 2018" "Shared Variable Save System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IntVariable \- Scriptable Ojbect for storing an int  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSharedVariableSaveSystem\&.SharedVariable< int >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnLoadData\fP (string data)"
.br
.RI "deserializes string into runtime data "
.ti -1c
.RI "override void \fBOnDrawElement\fP (Rect rect, float line_height)"
.br
.RI "draws the custom inspector for an element "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Scriptable Ojbect for storing an int 


.PP
Definition at line 11 of file IntVariable\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void IntVariable\&.OnDrawElement (Rect rect, float line_height)\fC [virtual]\fP"

.PP
draws the custom inspector for an element 
.PP
\fBParameters:\fP
.RS 4
\fIrect\fP size of element
.br
\fIline_height\fP height of a line
.RE
.PP
IListItemDrawer 
.PP
Reimplemented from \fBSharedVariableSaveSystem\&.SharedVariable< int >\fP\&.
.PP
Definition at line 29 of file IntVariable\&.cs\&.
.SS "override void IntVariable\&.OnLoadData (string data)"

.PP
deserializes string into runtime data 
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP serialized runtime data
.RE
.PP

.PP
Definition at line 17 of file IntVariable\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Shared Variable Save System from the source code\&.
