.TH "SharedVariableSaveSystem.Tests.VarTypes.IntVariableTests" 3 "Mon Oct 8 2018" "Shared Variable Save System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SharedVariableSaveSystem.Tests.VarTypes.IntVariableTests \- test fixture for int variable  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSharedVariableSaveSystem\&.Tests\&.VarTypes\&.SharedVariableTests< int >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override IEnumerator \fB_00_Setup\fP ()"
.br
.RI "setup test data "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
test fixture for int variable 


.PP
Definition at line 12 of file IntVariableTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override IEnumerator SharedVariableSaveSystem\&.Tests\&.VarTypes\&.IntVariableTests\&._00_Setup ()"

.PP
setup test data 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 21 of file IntVariableTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Shared Variable Save System from the source code\&.
