.TH "SharedVariableSaveSystem.Tests.VarTypes.RangeVariableTests< T >" 3 "Mon Oct 8 2018" "Shared Variable Save System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SharedVariableSaveSystem.Tests.VarTypes.RangeVariableTests< T > \- generic abstract test fixture for range variables  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSharedVariableSaveSystem\&.Tests\&.VarTypes\&.SharedVariableTests< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual IEnumerator \fB_30_Over\fP ()"
.br
.RI "Make sure that the has save works "
.ti -1c
.RI "virtual IEnumerator \fB_40_Under\fP ()"
.br
.RI "Make sure that the has save works "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRangeVariable\fP< T > \fBrangeVariable\fP"
.br
.ti -1c
.RI "float \fBmin\fP = 01"
.br
.ti -1c
.RI "float \fBmax\fP = 10"
.br
.in -1c
.SH "Detailed Description"
.PP 
generic abstract test fixture for range variables 


.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP generic type
.RE
.PP

.PP
Definition at line 12 of file RangeVariableTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual IEnumerator \fBSharedVariableSaveSystem\&.Tests\&.VarTypes\&.RangeVariableTests\fP< T >\&._30_Over ()\fC [virtual]\fP"

.PP
Make sure that the has save works 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 22 of file RangeVariableTests\&.cs\&.
.SS "virtual IEnumerator \fBSharedVariableSaveSystem\&.Tests\&.VarTypes\&.RangeVariableTests\fP< T >\&._40_Under ()\fC [virtual]\fP"

.PP
Make sure that the has save works 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 38 of file RangeVariableTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Shared Variable Save System from the source code\&.
