.TH "SharedVariableSaveSystem.Tests.SaveMethods.BinarySaveTests" 3 "Mon Oct 8 2018" "Shared Variable Save System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SharedVariableSaveSystem.Tests.SaveMethods.BinarySaveTests
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSharedVariableSaveSystem\&.Tests\&.SaveMethods\&.SaveMethodTests\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override IEnumerator \fB_1_SaveAndLoad\fP ()"
.br
.RI "Make sure that it can save and load data\&. Creates some test data\&. save test data\&. muddy test data\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file BinarySaveTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override IEnumerator SharedVariableSaveSystem\&.Tests\&.SaveMethods\&.BinarySaveTests\&._1_SaveAndLoad ()\fC [virtual]\fP"

.PP
Make sure that it can save and load data\&. Creates some test data\&. save test data\&. muddy test data\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Reimplemented from \fBSharedVariableSaveSystem\&.Tests\&.SaveMethods\&.SaveMethodTests\fP\&.
.PP
Definition at line 13 of file BinarySaveTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Shared Variable Save System from the source code\&.
