.TH "SharedVariableSaveSystem.Tests.VarTypes" 3 "Mon Oct 8 2018" "Shared Variable Save System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SharedVariableSaveSystem.Tests.VarTypes
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAttributeVariableTests\fP"
.br
.RI "test fixture for attribute variable "
.ti -1c
.RI "class \fBBoolVariableTests\fP"
.br
.RI "text fixture for bool varaible "
.ti -1c
.RI "class \fBFloatRangeVariableTests\fP"
.br
.RI "test fixture for float range variable "
.ti -1c
.RI "class \fBFloatVariableTests\fP"
.br
.RI "test fixture for float variable "
.ti -1c
.RI "class \fBIntRangeVariableTests\fP"
.br
.RI "test fixture for int range variable "
.ti -1c
.RI "class \fBIntVariableTests\fP"
.br
.RI "test fixture for int variable "
.ti -1c
.RI "class \fBRangeVariableTests\fP"
.br
.RI "generic abstract test fixture for range variables "
.ti -1c
.RI "class \fBSavableVariableTest\fP"
.br
.RI "test fixture for savable variables "
.ti -1c
.RI "class \fBSharedVariableTests\fP"
.br
.RI "generic abstract text fixture for shared variable "
.ti -1c
.RI "class \fBStringVariableTests\fP"
.br
.RI "test fixture for string variable "
.ti -1c
.RI "class \fBTransformVariableTests\fP"
.br
.RI "test fixture for transform variable "
.ti -1c
.RI "class \fBVector3IntVariableTests\fP"
.br
.RI "test fixture for vector3int variable "
.ti -1c
.RI "class \fBVector3VariableTests\fP"
.br
.RI "test fixture for vector3 variable "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Shared Variable Save System from the source code\&.
