.TH "SharedVariableSaveSystem.SaveSystemUtils" 3 "Mon Oct 8 2018" "Shared Variable Save System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SharedVariableSaveSystem.SaveSystemUtils \- some utility functions for the custom editors  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Texture2D \fBBase64ToTexture\fP (string base64)"
.br
.RI "converts a base64 image string into a texture2d image "
.in -1c
.SH "Detailed Description"
.PP 
some utility functions for the custom editors 


.PP
Definition at line 9 of file SaveSystemUtils\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static Texture2D SharedVariableSaveSystem\&.SaveSystemUtils\&.Base64ToTexture (string base64)\fC [static]\fP"

.PP
converts a base64 image string into a texture2d image 
.PP
\fBParameters:\fP
.RS 4
\fIbase64\fP base64 image
.RE
.PP
\fBReturns:\fP
.RS 4
Texture2D image
.RE
.PP

.PP
Definition at line 16 of file SaveSystemUtils\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Shared Variable Save System from the source code\&.
