.TH "SharedVariableSaveSystem.Tests.SaveMethods.SaveMethodTests" 3 "Mon Oct 8 2018" "Shared Variable Save System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SharedVariableSaveSystem.Tests.SaveMethods.SaveMethodTests \- test fixture for save methods  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSharedVariableSaveSystem\&.Tests\&.SaveMethods\&.BinarySaveTests\fP, and \fBSharedVariableSaveSystem\&.Tests\&.SaveMethods\&.SavePlayerPrefsTests\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual IEnumerator \fB_1_SaveAndLoad\fP ()"
.br
.RI "Make sure that it can save and load data\&. Creates some test data\&. save test data\&. muddy test data\&. "
.ti -1c
.RI "virtual IEnumerator \fB_2_HasSave\fP ()"
.br
.RI "Make sure that the has save works "
.ti -1c
.RI "virtual IEnumerator \fB_3_LastSave\fP ()"
.br
.RI "Make sure that the has save works "
.ti -1c
.RI "virtual IEnumerator \fB_4_ClearData\fP ()"
.br
.RI "Make sure that clearing data works "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Dictionary< int, string > \fBtestData\fP = new Dictionary<int, string>()"
.br
.ti -1c
.RI "\fBSaveMethod\fP \fBsaveMethod\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
test fixture for save methods 


.PP
Definition at line 14 of file SaveMethodTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual IEnumerator SharedVariableSaveSystem\&.Tests\&.SaveMethods\&.SaveMethodTests\&._1_SaveAndLoad ()\fC [virtual]\fP"

.PP
Make sure that it can save and load data\&. Creates some test data\&. save test data\&. muddy test data\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Reimplemented in \fBSharedVariableSaveSystem\&.Tests\&.SaveMethods\&.BinarySaveTests\fP, and \fBSharedVariableSaveSystem\&.Tests\&.SaveMethods\&.SavePlayerPrefsTests\fP\&.
.PP
Definition at line 26 of file SaveMethodTests\&.cs\&.
.SS "virtual IEnumerator SharedVariableSaveSystem\&.Tests\&.SaveMethods\&.SaveMethodTests\&._2_HasSave ()\fC [virtual]\fP"

.PP
Make sure that the has save works 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 49 of file SaveMethodTests\&.cs\&.
.SS "virtual IEnumerator SharedVariableSaveSystem\&.Tests\&.SaveMethods\&.SaveMethodTests\&._3_LastSave ()\fC [virtual]\fP"

.PP
Make sure that the has save works 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 63 of file SaveMethodTests\&.cs\&.
.SS "virtual IEnumerator SharedVariableSaveSystem\&.Tests\&.SaveMethods\&.SaveMethodTests\&._4_ClearData ()\fC [virtual]\fP"

.PP
Make sure that clearing data works 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 78 of file SaveMethodTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Shared Variable Save System from the source code\&.
