.TH "SharedVariableSaveSystem.Tests.VarTypes.FloatVariableTests" 3 "Mon Oct 8 2018" "Shared Variable Save System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SharedVariableSaveSystem.Tests.VarTypes.FloatVariableTests
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSharedVariableSaveSystem\&.Tests\&.VarTypes\&.SharedVariableTests< float >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override IEnumerator \fB_00_Setup\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 9 of file FloatVariableTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Shared Variable Save System from the source code\&.
