.TH "SharedVariableSaveSystem.IListItemDrawer" 3 "Mon Oct 8 2018" "Shared Variable Save System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SharedVariableSaveSystem.IListItemDrawer \- interface for displaying custom property drawers for items in orderable list  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSharedVariableSaveSystem\&.SaveMethod\fP, \fBSharedVariableSaveSystem\&.SharedVariable< T >\fP, and \fBTransformVariable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnDrawElement\fP (Rect rect, float line_height)"
.br
.RI "draws the custom inspector for an element in the list "
.ti -1c
.RI "float \fBGetElementHeight\fP (float line_height)"
.br
.RI "returns the height of the element in the list "
.in -1c
.SH "Detailed Description"
.PP 
interface for displaying custom property drawers for items in orderable list 


.PP
Definition at line 9 of file IListItemDrawer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "float SharedVariableSaveSystem\&.IListItemDrawer\&.GetElementHeight (float line_height)"

.PP
returns the height of the element in the list 
.PP
\fBParameters:\fP
.RS 4
\fIline_height\fP height of a line
.RE
.PP
\fBReturns:\fP
.RS 4
height of element
.RE
.PP

.PP
Implemented in \fBSharedVariableSaveSystem\&.SaveBinaryFile\fP, \fBTransformVariable\fP, \fBSharedVariableSaveSystem\&.SharedVariable< T >\fP, and \fBSharedVariableSaveSystem\&.SaveMethod\fP\&.
.SS "void SharedVariableSaveSystem\&.IListItemDrawer\&.OnDrawElement (Rect rect, float line_height)"

.PP
draws the custom inspector for an element in the list 
.PP
\fBParameters:\fP
.RS 4
\fIrect\fP the area to draw
.br
\fIline_height\fP height of a line
.RE
.PP

.PP
Implemented in \fBSharedVariableSaveSystem\&.SaveBinaryFile\fP, \fBTransformVariable\fP, \fBSharedVariableSaveSystem\&.SharedVariable< T >\fP, and \fBSharedVariableSaveSystem\&.SaveMethod\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Shared Variable Save System from the source code\&.
