.TH "SharedVariableSaveSystem.SaveObjectEditor" 3 "Mon Oct 8 2018" "Shared Variable Save System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SharedVariableSaveSystem.SaveObjectEditor \- Custome editor for save objects  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Editor\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInspectorGUI\fP ()"
.br
.RI "Draw the custom inspector "
.ti -1c
.RI "override Texture2D \fBRenderStaticPreview\fP (string assetPath, Object[] subAssets, int width, int height)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSaveObject\fP \fBsaveObject\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Custome editor for save objects 


.PP
Definition at line 14 of file SaveObjectEditor\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void SharedVariableSaveSystem\&.SaveObjectEditor\&.OnInspectorGUI ()"

.PP
Draw the custom inspector 
.PP
Definition at line 170 of file SaveObjectEditor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Shared Variable Save System from the source code\&.
