.TH "SharedVariableSaveSystem.Tests.SaveObjectTest" 3 "Mon Oct 8 2018" "Shared Variable Save System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SharedVariableSaveSystem.Tests.SaveObjectTest \- test fixture for save object  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "IEnumerator \fB_1_Setup\fP ()"
.br
.ti -1c
.RI "IEnumerator \fB_2_Save\fP ()"
.br
.ti -1c
.RI "IEnumerator \fB_3_Load\fP ()"
.br
.ti -1c
.RI "IEnumerator \fB_4_Clear\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
test fixture for save object 


.PP
Definition at line 13 of file SaveObjectTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Shared Variable Save System from the source code\&.
