.TH "SharedVariableSaveSystem.Tests.VarTypes.TransformVariableTests" 3 "Mon Oct 8 2018" "Shared Variable Save System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SharedVariableSaveSystem.Tests.VarTypes.TransformVariableTests \- test fixture for transform variable  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSharedVariableSaveSystem\&.Tests\&.VarTypes\&.SavableVariableTest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override IEnumerator \fB_00_Setup\fP ()"
.br
.RI "setup test data "
.ti -1c
.RI "IEnumerator \fB_30_SetTransform\fP ()"
.br
.RI "validate that it can get data from a transform referense "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
test fixture for transform variable 


.PP
Definition at line 12 of file TransformVariableTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override IEnumerator SharedVariableSaveSystem\&.Tests\&.VarTypes\&.TransformVariableTests\&._00_Setup ()\fC [virtual]\fP"

.PP
setup test data 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Implements \fBSharedVariableSaveSystem\&.Tests\&.VarTypes\&.SavableVariableTest\fP\&.
.PP
Definition at line 24 of file TransformVariableTests\&.cs\&.
.SS "IEnumerator SharedVariableSaveSystem\&.Tests\&.VarTypes\&.TransformVariableTests\&._30_SetTransform ()"

.PP
validate that it can get data from a transform referense 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 54 of file TransformVariableTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Shared Variable Save System from the source code\&.
