.TH "SharedVariableSaveSystem.Tests.VarTypes.SharedVariableTests< T >" 3 "Mon Oct 8 2018" "Shared Variable Save System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SharedVariableSaveSystem.Tests.VarTypes.SharedVariableTests< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSharedVariableSaveSystem\&.Tests\&.VarTypes\&.SavableVariableTest\fP\&.
.PP
Inherited by \fBSharedVariableSaveSystem\&.Tests\&.VarTypes\&.RangeVariableTests< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override IEnumerator \fB_00_Setup\fP ()"
.br
.RI "setup the savableVariable "
.ti -1c
.RI "virtual IEnumerator \fB_80_Muddy\fP ()"
.br
.RI "Make sure that the has save works "
.ti -1c
.RI "virtual IEnumerator \fB_90_Reset\fP ()"
.br
.RI "Make sure that the has save works "
.ti -1c
.RI "virtual IEnumerator \fB_99_Passes\fP ()"
.br
.RI "Make sure that the has save works "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSharedVariable\fP< T > \fBsharedVariable\fP"
.br
.ti -1c
.RI "T \fBiVal\fP"
.br
.ti -1c
.RI "T \fBrVal\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file SharedVariableTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override IEnumerator \fBSharedVariableSaveSystem\&.Tests\&.VarTypes\&.SharedVariableTests\fP< T >\&._00_Setup ()\fC [virtual]\fP"

.PP
setup the savableVariable 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Implements \fBSharedVariableSaveSystem\&.Tests\&.VarTypes\&.SavableVariableTest\fP\&.
.PP
Definition at line 15 of file SharedVariableTests\&.cs\&.
.SS "virtual IEnumerator \fBSharedVariableSaveSystem\&.Tests\&.VarTypes\&.SharedVariableTests\fP< T >\&._80_Muddy ()\fC [virtual]\fP"

.PP
Make sure that the has save works 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 31 of file SharedVariableTests\&.cs\&.
.SS "virtual IEnumerator \fBSharedVariableSaveSystem\&.Tests\&.VarTypes\&.SharedVariableTests\fP< T >\&._90_Reset ()\fC [virtual]\fP"

.PP
Make sure that the has save works 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 43 of file SharedVariableTests\&.cs\&.
.SS "virtual IEnumerator \fBSharedVariableSaveSystem\&.Tests\&.VarTypes\&.SharedVariableTests\fP< T >\&._99_Passes ()\fC [virtual]\fP"

.PP
Make sure that the has save works 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 56 of file SharedVariableTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Shared Variable Save System from the source code\&.
