.TH "SharedVariableSaveSystem.RangeVariable< T >" 3 "Mon Oct 8 2018" "Shared Variable Save System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SharedVariableSaveSystem.RangeVariable< T > \- Base abstract class for a range variable\&. Adds range limit utils  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSharedVariableSaveSystem\&.SharedVariable< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBFitToRange\fP ()"
.br
.RI "Ensures that the float value is within the min and max of the range\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBMinValue\fP"
.br
.RI "Lowest possible value "
.ti -1c
.RI "float \fBMaxValue\fP"
.br
.RI "Largest possible value "
.ti -1c
.RI "bool \fBDescending\fP"
.br
.RI "Inverts the percentage value of the range\&. MaxValue becomes 0% of the range "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "abstract float \fBFloatValue\fP\fC [get, set]\fP"
.br
.RI "Value used to calculate percentage of range\&. "
.ti -1c
.RI "float \fBPercent\fP\fC [get, set]\fP"
.br
.RI "Where the Runtime value is between the min and max values of the range\&. "
.in -1c
.SH "Detailed Description"
.PP 
Base abstract class for a range variable\&. Adds range limit utils 


.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Type of value for the range variable
.RE
.PP

.PP
Definition at line 10 of file RangeVariable\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBSharedVariableSaveSystem\&.RangeVariable\fP< T >\&.FitToRange ()"

.PP
Ensures that the float value is within the min and max of the range\&. 
.PP
Definition at line 54 of file RangeVariable\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool \fBSharedVariableSaveSystem\&.RangeVariable\fP< T >\&.Descending"

.PP
Inverts the percentage value of the range\&. MaxValue becomes 0% of the range 
.PP
Definition at line 23 of file RangeVariable\&.cs\&.
.SS "float \fBSharedVariableSaveSystem\&.RangeVariable\fP< T >\&.MaxValue"

.PP
Largest possible value 
.PP
Definition at line 19 of file RangeVariable\&.cs\&.
.SS "float \fBSharedVariableSaveSystem\&.RangeVariable\fP< T >\&.MinValue"

.PP
Lowest possible value 
.PP
Definition at line 15 of file RangeVariable\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "abstract float \fBSharedVariableSaveSystem\&.RangeVariable\fP< T >\&.FloatValue\fC [get]\fP, \fC [set]\fP"

.PP
Value used to calculate percentage of range\&. Used to access RuntimeValue for percent calculations
.PP
Definition at line 28 of file RangeVariable\&.cs\&.
.SS "float \fBSharedVariableSaveSystem\&.RangeVariable\fP< T >\&.Percent\fC [get]\fP, \fC [set]\fP"

.PP
Where the Runtime value is between the min and max values of the range\&. MinValue is 0% (0\&.0f) and Max Value is 100% (1\&.0f)
.PP
If Descending is true MinValue is 100% and MaxValue is 0%
.PP
Definition at line 35 of file RangeVariable\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Shared Variable Save System from the source code\&.
