.TH "SharedVariableSaveSystem.Tests.SaveMethods" 3 "Mon Oct 8 2018" "Shared Variable Save System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SharedVariableSaveSystem.Tests.SaveMethods
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBinarySaveTests\fP"
.br
.RI "test fixture for save to binary file "
.ti -1c
.RI "class \fBSaveMethodTests\fP"
.br
.RI "test fixture for save methods "
.ti -1c
.RI "class \fBSavePlayerPrefsTests\fP"
.br
.RI "test fixture for save to player prefs "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Shared Variable Save System from the source code\&.
