.TH "SharedVariableSaveSystem" 3 "Mon Oct 8 2018" "Shared Variable Save System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SharedVariableSaveSystem
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBIListItemDrawer\fP"
.br
.RI "interface for displaying custom property drawers for items in orderable list "
.ti -1c
.RI "interface \fBISaveMethod\fP"
.br
.RI "interface for the basics of save methods\&. "
.ti -1c
.RI "interface \fBISaveVariable\fP"
.br
.RI "interface for a save variable "
.ti -1c
.RI "class \fBRangeVariable\fP"
.br
.RI "Base abstract class for a range variable\&. Adds range limit utils "
.ti -1c
.RI "class \fBSavableVariable\fP"
.br
.RI "Base abstract class for savable variables\&. Used with Save Object to save and load data\&. "
.ti -1c
.RI "class \fBSaveBinaryFile\fP"
.br
.RI "Saves a binary file to the local disk\&. "
.ti -1c
.RI "class \fBSaveMethod\fP"
.br
.RI "base class for save methods "
.ti -1c
.RI "class \fBSaveObject\fP"
.br
.RI "Holds a set of references to Savable Variables and Save Methods\&. "
.ti -1c
.RI "class \fBSaveObjectEditor\fP"
.br
.RI "Custome editor for save objects "
.ti -1c
.RI "class \fBSavePlayerPrefs\fP"
.br
.RI "Saves data using PlayerPrefs "
.ti -1c
.RI "class \fBSaveSystemUtils\fP"
.br
.RI "some utility functions for the custom editors "
.ti -1c
.RI "class \fBSharedVariable\fP"
.br
.RI "Base abstract class for Scriptable Object variables\&. Extend this class to create new Savable Shared Variables\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Shared Variable Save System from the source code\&.
