.TH "SharedVariableSaveSystem.Tests.VarTypes" 3 "Mon Oct 8 2018" "Shared Variable Save System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SharedVariableSaveSystem.Tests.VarTypes
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAttributeVariableTests\fP"
.br
.ti -1c
.RI "class \fBBoolVariableTests\fP"
.br
.ti -1c
.RI "class \fBFloatRangeVariableTests\fP"
.br
.ti -1c
.RI "class \fBFloatVariableTests\fP"
.br
.ti -1c
.RI "class \fBIntRangeVariableTests\fP"
.br
.ti -1c
.RI "class \fBIntVariableTests\fP"
.br
.ti -1c
.RI "class \fBRangeVariableTests\fP"
.br
.ti -1c
.RI "class \fBSavableVariableTest\fP"
.br
.ti -1c
.RI "class \fBSharedVariableTests\fP"
.br
.ti -1c
.RI "class \fBStringVariableTests\fP"
.br
.ti -1c
.RI "class \fBTransformVariableTests\fP"
.br
.ti -1c
.RI "class \fBVector3IntVariableTests\fP"
.br
.ti -1c
.RI "class \fBVector3VariableTests\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Shared Variable Save System from the source code\&.
