.TH "SharedVariableSaveSystem.Tests.VarTypes.SavableVariableTest" 3 "Mon Oct 8 2018" "Shared Variable Save System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SharedVariableSaveSystem.Tests.VarTypes.SavableVariableTest \- test fixture for savable variables  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSharedVariableSaveSystem\&.Tests\&.VarTypes\&.SharedVariableTests< T >\fP, and \fBSharedVariableSaveSystem\&.Tests\&.VarTypes\&.TransformVariableTests\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract IEnumerator \fB_00_Setup\fP ()"
.br
.RI "setup the savableVariable "
.ti -1c
.RI "virtual IEnumerator \fB_10_Save\fP ()"
.br
.RI "Make sure that the has save works "
.ti -1c
.RI "virtual IEnumerator \fB_20_Load\fP ()"
.br
.RI "Make sure that the has save works "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSavableVariable\fP \fBsavableVariable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
test fixture for savable variables 


.PP
Definition at line 11 of file SavableVariableTest\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "abstract IEnumerator SharedVariableSaveSystem\&.Tests\&.VarTypes\&.SavableVariableTest\&._00_Setup ()\fC [pure virtual]\fP"

.PP
setup the savableVariable 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Implemented in \fBSharedVariableSaveSystem\&.Tests\&.VarTypes\&.TransformVariableTests\fP, and \fBSharedVariableSaveSystem\&.Tests\&.VarTypes\&.SharedVariableTests< T >\fP\&.
.SS "virtual IEnumerator SharedVariableSaveSystem\&.Tests\&.VarTypes\&.SavableVariableTest\&._10_Save ()\fC [virtual]\fP"

.PP
Make sure that the has save works 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 26 of file SavableVariableTest\&.cs\&.
.SS "virtual IEnumerator SharedVariableSaveSystem\&.Tests\&.VarTypes\&.SavableVariableTest\&._20_Load ()\fC [virtual]\fP"

.PP
Make sure that the has save works 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 44 of file SavableVariableTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Shared Variable Save System from the source code\&.
