.TH "Vector3IntVariable" 3 "Mon Oct 8 2018" "Shared Variable Save System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vector3IntVariable \- Scriptable Object for storing a Vector3Int  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSharedVariableSaveSystem\&.SharedVariable< Vector3Int >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnLoadData\fP (string data)"
.br
.RI "deserializes string into runtime data "
.ti -1c
.RI "override string \fBOnSaveData\fP ()"
.br
.RI "serializes runtime data into a string "
.ti -1c
.RI "override void \fBOnDrawElement\fP (Rect rect, float line_height)"
.br
.RI "draws the custom inspector for an element "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Scriptable Object for storing a Vector3Int 


.PP
Definition at line 12 of file Vector3IntVariable\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Vector3IntVariable\&.OnDrawElement (Rect rect, float line_height)\fC [virtual]\fP"

.PP
draws the custom inspector for an element 
.PP
\fBParameters:\fP
.RS 4
\fIrect\fP size of element
.br
\fIline_height\fP height of a line
.RE
.PP
IListItemDrawer 
.PP
Reimplemented from \fBSharedVariableSaveSystem\&.SharedVariable< Vector3Int >\fP\&.
.PP
Definition at line 39 of file Vector3IntVariable\&.cs\&.
.SS "override void Vector3IntVariable\&.OnLoadData (string data)"

.PP
deserializes string into runtime data 
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP serialized runtime data
.RE
.PP

.PP
Definition at line 18 of file Vector3IntVariable\&.cs\&.
.SS "override string Vector3IntVariable\&.OnSaveData ()"

.PP
serializes runtime data into a string 
.PP
\fBReturns:\fP
.RS 4
serialized string of runtime data
.RE
.PP

.PP
Definition at line 28 of file Vector3IntVariable\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Shared Variable Save System from the source code\&.
