var searchData=
[
  ['savablevariable',['SavableVariable',['../class_shared_variable_save_system_1_1_savable_variable.html',1,'SharedVariableSaveSystem']]],
  ['savablevariabletest',['SavableVariableTest',['../class_shared_variable_save_system_1_1_tests_1_1_var_types_1_1_savable_variable_test.html',1,'SharedVariableSaveSystem::Tests::VarTypes']]],
  ['savebinaryfile',['SaveBinaryFile',['../class_shared_variable_save_system_1_1_save_binary_file.html',1,'SharedVariableSaveSystem']]],
  ['savedata',['SaveData',['../interface_shared_variable_save_system_1_1_i_save_method.html#a13b6199eb4ca5365b703ef815c51a8d2',1,'SharedVariableSaveSystem.ISaveMethod.SaveData()'],['../class_shared_variable_save_system_1_1_save_method.html#a83e026fb23241bdd52865666756fb296',1,'SharedVariableSaveSystem.SaveMethod.SaveData()'],['../class_shared_variable_save_system_1_1_save_binary_file.html#a289ff2281c4519c2d4ca5b53cb43e011',1,'SharedVariableSaveSystem.SaveBinaryFile.SaveData()'],['../class_shared_variable_save_system_1_1_save_player_prefs.html#a22454bd935cef024175ac395184dcba2',1,'SharedVariableSaveSystem.SavePlayerPrefs.SaveData()'],['../class_shared_variable_save_system_1_1_save_object.html#ad607935fa34cc56e3c307b0c3de35fab',1,'SharedVariableSaveSystem.SaveObject.SaveData()']]],
  ['saveextension',['SaveExtension',['../class_shared_variable_save_system_1_1_save_binary_file.html#af2ea61d0418257c644ff5386cd0a0e34',1,'SharedVariableSaveSystem::SaveBinaryFile']]],
  ['savefilepath',['SaveFilePath',['../class_shared_variable_save_system_1_1_save_method.html#a649f71341c5c9c3b2d5ff64c29f8231b',1,'SharedVariableSaveSystem::SaveMethod']]],
  ['savelocations',['SaveLocations',['../class_shared_variable_save_system_1_1_save_object.html#a8e51b0771ec31ba72478b54d07e38da0',1,'SharedVariableSaveSystem::SaveObject']]],
  ['savemethod',['SaveMethod',['../class_shared_variable_save_system_1_1_save_method.html',1,'SharedVariableSaveSystem']]],
  ['savemethods',['SaveMethods',['../namespace_shared_variable_save_system_1_1_tests_1_1_save_methods.html',1,'SharedVariableSaveSystem::Tests']]],
  ['savemethodtests',['SaveMethodTests',['../class_shared_variable_save_system_1_1_tests_1_1_save_methods_1_1_save_method_tests.html',1,'SharedVariableSaveSystem::Tests::SaveMethods']]],
  ['savename',['SaveName',['../interface_shared_variable_save_system_1_1_i_save_method.html#a78db91e806bd016a2950e985cad7558e',1,'SharedVariableSaveSystem.ISaveMethod.SaveName()'],['../class_shared_variable_save_system_1_1_save_method.html#a7ba38c658a2d42bae23d88bcc61f1840',1,'SharedVariableSaveSystem.SaveMethod.SaveName()'],['../class_shared_variable_save_system_1_1_save_binary_file.html#a0dc7edeed2ea133186f15c7c166072ea',1,'SharedVariableSaveSystem.SaveBinaryFile.SaveName()'],['../class_shared_variable_save_system_1_1_save_player_prefs.html#a4ea085aa0886c4d7571ca2c34f876e30',1,'SharedVariableSaveSystem.SavePlayerPrefs.SaveName()']]],
  ['saveobject',['SaveObject',['../class_shared_variable_save_system_1_1_save_object.html',1,'SharedVariableSaveSystem']]],
  ['saveobjecteditor',['SaveObjectEditor',['../class_shared_variable_save_system_1_1_save_object_editor.html',1,'SharedVariableSaveSystem']]],
  ['saveobjecttest',['SaveObjectTest',['../class_shared_variable_save_system_1_1_tests_1_1_save_object_test.html',1,'SharedVariableSaveSystem::Tests']]],
  ['savepath',['SavePath',['../class_shared_variable_save_system_1_1_save_method.html#a81192e8f64a9253733723d0f6c47c605',1,'SharedVariableSaveSystem.SaveMethod.SavePath()'],['../class_shared_variable_save_system_1_1_save_binary_file.html#ac0235a1af16f083ed2ce038012ae48de',1,'SharedVariableSaveSystem.SaveBinaryFile.SavePath()'],['../class_shared_variable_save_system_1_1_save_player_prefs.html#a8493b19477e32e760d71b9fbc789b834',1,'SharedVariableSaveSystem.SavePlayerPrefs.SavePath()']]],
  ['saveplayerprefs',['SavePlayerPrefs',['../class_shared_variable_save_system_1_1_save_player_prefs.html',1,'SharedVariableSaveSystem']]],
  ['saveplayerprefstests',['SavePlayerPrefsTests',['../class_shared_variable_save_system_1_1_tests_1_1_save_methods_1_1_save_player_prefs_tests.html',1,'SharedVariableSaveSystem::Tests::SaveMethods']]],
  ['savesystemutils',['SaveSystemUtils',['../class_shared_variable_save_system_1_1_save_system_utils.html',1,'SharedVariableSaveSystem']]],
  ['sharedvariable',['SharedVariable',['../class_shared_variable_save_system_1_1_shared_variable.html',1,'SharedVariableSaveSystem']]],
  ['sharedvariable_3c_20bool_20_3e',['SharedVariable&lt; bool &gt;',['../class_shared_variable_save_system_1_1_shared_variable.html',1,'SharedVariableSaveSystem']]],
  ['sharedvariable_3c_20float_20_3e',['SharedVariable&lt; float &gt;',['../class_shared_variable_save_system_1_1_shared_variable.html',1,'SharedVariableSaveSystem']]],
  ['sharedvariable_3c_20int_20_3e',['SharedVariable&lt; int &gt;',['../class_shared_variable_save_system_1_1_shared_variable.html',1,'SharedVariableSaveSystem']]],
  ['sharedvariable_3c_20string_20_3e',['SharedVariable&lt; string &gt;',['../class_shared_variable_save_system_1_1_shared_variable.html',1,'SharedVariableSaveSystem']]],
  ['sharedvariable_3c_20vector3_20_3e',['SharedVariable&lt; Vector3 &gt;',['../class_shared_variable_save_system_1_1_shared_variable.html',1,'SharedVariableSaveSystem']]],
  ['sharedvariable_3c_20vector3int_20_3e',['SharedVariable&lt; Vector3Int &gt;',['../class_shared_variable_save_system_1_1_shared_variable.html',1,'SharedVariableSaveSystem']]],
  ['sharedvariablesavesystem',['SharedVariableSaveSystem',['../namespace_shared_variable_save_system.html',1,'']]],
  ['sharedvariabletests',['SharedVariableTests',['../class_shared_variable_save_system_1_1_tests_1_1_var_types_1_1_shared_variable_tests.html',1,'SharedVariableSaveSystem::Tests::VarTypes']]],
  ['sharedvariabletests_3c_20bool_20_3e',['SharedVariableTests&lt; bool &gt;',['../class_shared_variable_save_system_1_1_tests_1_1_var_types_1_1_shared_variable_tests.html',1,'SharedVariableSaveSystem::Tests::VarTypes']]],
  ['sharedvariabletests_3c_20float_20_3e',['SharedVariableTests&lt; float &gt;',['../class_shared_variable_save_system_1_1_tests_1_1_var_types_1_1_shared_variable_tests.html',1,'SharedVariableSaveSystem::Tests::VarTypes']]],
  ['sharedvariabletests_3c_20int_20_3e',['SharedVariableTests&lt; int &gt;',['../class_shared_variable_save_system_1_1_tests_1_1_var_types_1_1_shared_variable_tests.html',1,'SharedVariableSaveSystem::Tests::VarTypes']]],
  ['sharedvariabletests_3c_20string_20_3e',['SharedVariableTests&lt; string &gt;',['../class_shared_variable_save_system_1_1_tests_1_1_var_types_1_1_shared_variable_tests.html',1,'SharedVariableSaveSystem::Tests::VarTypes']]],
  ['sharedvariabletests_3c_20vector3_20_3e',['SharedVariableTests&lt; Vector3 &gt;',['../class_shared_variable_save_system_1_1_tests_1_1_var_types_1_1_shared_variable_tests.html',1,'SharedVariableSaveSystem::Tests::VarTypes']]],
  ['sharedvariabletests_3c_20vector3int_20_3e',['SharedVariableTests&lt; Vector3Int &gt;',['../class_shared_variable_save_system_1_1_tests_1_1_var_types_1_1_shared_variable_tests.html',1,'SharedVariableSaveSystem::Tests::VarTypes']]],
  ['stringvariable',['StringVariable',['../class_string_variable.html',1,'']]],
  ['stringvariableeditor',['StringVariableEditor',['../class_string_variable_editor.html',1,'']]],
  ['stringvariabletests',['StringVariableTests',['../class_shared_variable_save_system_1_1_tests_1_1_var_types_1_1_string_variable_tests.html',1,'SharedVariableSaveSystem::Tests::VarTypes']]],
  ['tests',['Tests',['../namespace_shared_variable_save_system_1_1_tests.html',1,'SharedVariableSaveSystem']]],
  ['vartypes',['VarTypes',['../namespace_shared_variable_save_system_1_1_tests_1_1_var_types.html',1,'SharedVariableSaveSystem::Tests']]]
];
