var namespace_shared_variable_save_system_1_1_tests_1_1_save_methods =
[
    [ "BinarySaveTests", "class_shared_variable_save_system_1_1_tests_1_1_save_methods_1_1_binary_save_tests.html", "class_shared_variable_save_system_1_1_tests_1_1_save_methods_1_1_binary_save_tests" ],
    [ "SaveMethodTests", "class_shared_variable_save_system_1_1_tests_1_1_save_methods_1_1_save_method_tests.html", "class_shared_variable_save_system_1_1_tests_1_1_save_methods_1_1_save_method_tests" ],
    [ "SavePlayerPrefsTests", "class_shared_variable_save_system_1_1_tests_1_1_save_methods_1_1_save_player_prefs_tests.html", "class_shared_variable_save_system_1_1_tests_1_1_save_methods_1_1_save_player_prefs_tests" ]
];